name: github-actions-demo

on:
  push:

jobs:
  summa:
    runs-on: ubuntu-latest
    steps:
      - name: downloading
        uses: actions/checkout@v7

      - name: checking
        run: ls

      - name: printing
        run: echo "Hello from GitHub Actions!"
      